#!/usr/bin/env python3
"""
HardSID 4U — milestone 7: captured init + our own note.

The replay proved the transport. The remaining question is narrow: was the
missing ingredient the INIT sequence that ACID64 sends before any music?

This sends the first 5 captured transfers verbatim (the init), then a note
generated by our own code. If it sings, we own the protocol completely and
the init is just a sequence to reproduce.

Usage:
  python3 hs4u_m7_note_after_init.py                 # init + 440 Hz on chip 0
  python3 hs4u_m7_note_after_init.py --chip 2
  python3 hs4u_m7_note_after_init.py --no-init       # control: note alone
"""
import argparse
import json
import os
import struct
import sys
import time

import usb1

VID, PID = 0x6581, 0x8580
IFACE = 0
EP_IN, EP_OUT = 0x81, 0x02
BLOCK = 512
RING = 0x2000
TIMEOUT = 1000
FILLER = b"\xff\xff"
PAL_CLOCK = 985248

HERE = os.path.dirname(os.path.abspath(__file__))
BLOB = os.path.join(HERE, "hs4u_capture_writes.bin")
INDEX = os.path.join(HERE, "hs4u_capture_writes.json")


# Verified against the capture:
#   word = data byte first, then command byte
#   cmd 0x00-0x7F = (chip << 5) | reg
#   cmd 0xEF = delay high byte, emitted BEFORE 0xEE = delay low byte
#   cmd 0xFF = filler
def cmd(c, d):
    return bytes((d & 0xFF, c & 0xFF))


def reg(chip, r, d):
    return cmd(((chip & 3) << 5) | (r & 0x1F), d)


def delay(cycles):
    out = b""
    while cycles > 0:
        n = min(cycles, 0xFFFF)
        if n >= 0x100:
            out += cmd(0xEF, n >> 8)
        if n & 0xFF:
            out += cmd(0xEE, n & 0xFF)
        cycles -= n
    return out


def ptrs(h):
    raw = bytes(h.bulkRead(EP_IN, 64, timeout=TIMEOUT))
    rd, wr, state = struct.unpack_from("<HHH", raw, 0x1A)
    used = (wr - rd) & (RING - 1)
    return rd, wr, state, RING - used


def ensure_started(h):
    rd, wr, state, free = ptrs(h)
    print(f"[link] rd={rd:#06x} wr={wr:#06x} state={state:#06x} free={free}")
    if state & 0x80:
        print("  engine already running")
        return
    for _ in range(8):
        if ptrs(h)[3] >= 1024:
            h.bulkWrite(EP_OUT, FILLER * 256, timeout=TIMEOUT)
            time.sleep(0.15)
            if ptrs(h)[2] & 0x80:
                print("  started (filler block)")
                return
        h.bulkWrite(EP_OUT, b"\xff\xff\x01\x00", timeout=TIMEOUT)
        time.sleep(0.15)
        if ptrs(h)[2] & 0x80:
            print("  started (short packet)")
            return
    sys.exit("  could not start engine - power-cycle and retry")


def send(h, payload, label=""):
    payload += FILLER * (((-len(payload)) % BLOCK) // 2)
    for i in range(0, len(payload), BLOCK):
        for _ in range(5000):
            if ptrs(h)[3] >= BLOCK * 2:
                break
            time.sleep(0.002)
        h.bulkWrite(EP_OUT, payload[i:i + BLOCK], timeout=TIMEOUT)
    rd, wr, state, free = ptrs(h)
    print(f"  {label} sent {len(payload)} bytes  "
          f"rd={rd:#06x} wr={wr:#06x} state={state:#06x} free={free}")


def drain(h, limit=30):
    t0 = time.time()
    while time.time() - t0 < limit:
        if ptrs(h)[3] >= RING - BLOCK:
            return
        time.sleep(0.05)


def note(chip, hz, seconds):
    freq = int(round(hz * 16777216 / PAL_CLOCK)) & 0xFFFF
    s = b""
    s += reg(chip, 0x18, 0x0F) + delay(8)      # volume
    s += reg(chip, 0x05, 0x11) + delay(8)      # attack/decay
    s += reg(chip, 0x06, 0xF1) + delay(8)      # sustain/release
    s += reg(chip, 0x00, freq & 0xFF) + delay(8)
    s += reg(chip, 0x01, (freq >> 8) & 0xFF) + delay(8)
    s += reg(chip, 0x04, 0x11) + delay(int(PAL_CLOCK * seconds))   # tri+gate
    s += reg(chip, 0x04, 0x10) + delay(int(PAL_CLOCK * 0.4))       # gate off
    return s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--chip", type=int, default=0)
    ap.add_argument("--hz", type=float, default=440.0)
    ap.add_argument("--seconds", type=float, default=1.5)
    ap.add_argument("--no-init", action="store_true")
    args = ap.parse_args()

    with usb1.USBContext() as ctx:
        h = ctx.openByVendorIDAndProductID(VID, PID, skip_on_error=True)
        if h is None:
            sys.exit("device not found")
        h.claimInterface(IFACE)
        try:
            ensure_started(h)

            if not args.no_init:
                blob = open(BLOB, "rb").read()
                idx = json.load(open(INDEX))[:5]
                init = blob[:idx[-1]["off"] + idx[-1]["len"]]
                print(f"\n[init] replaying captured init, {len(init)} bytes")
                send(h, init, "init")
                drain(h)
            else:
                print("\n[init] SKIPPED (control run)")

            print(f"\n[note] chip {args.chip}, {args.hz} Hz, {args.seconds}s "
                  "- listen on the black 'mixed out' jack")
            send(h, note(args.chip, args.hz, args.seconds), "note")
            drain(h)

            print("\n  init + note -> tone?  the init was the missing piece")
            print("  --no-init    -> tone?  the init is not needed after all")
        finally:
            h.releaseInterface(IFACE)


if __name__ == "__main__":
    main()
